# Generated by Django 5.1.6 on 2025-03-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
