# Generated by Django 5.1.6 on 2025-03-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_tenant_address_remove_tenant_contact_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='user',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='MaintenanceRequest',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
